development:
  adapter: postgresql
  host: localhost
  database: sethgrotelueschen_development

test:
  adapter: postgresql
  host: localhost
  database: sethgrotelueschen_test

production:
  adapter: postgresql
  host: localhost
  database: sethgrotelueschen_production